### ISSUE TITLE
Can you provide the requirements .txt file during installation?

### ISSUE THREAD

**Issue by dj1367250510** [zhujunli1993/SwinDePose#6]
When I used the environment file you provided to import the environment, a lot of problems occurred, I would like to ask you to provide me with the requirements .txt files required for installation, look forward to your reply!

**Comment by henryhskim** [comment]
did you figured out the problems while setting the environment? because whenever I use the yml file to create the conda environment, it shows me the error just like the photo below.

<img width="570" alt="image" src="https://github.com/zhujunli1993/SwinDePose/assets/39149858/9d3f5be2-ad63-47a8-bf26-b4db5660b135">

**Comment by dj1367250510** [comment]
i  meet the problem  likes:mmcv-full .pucuda could not

**Comment by dj1367250510** [comment]
i  meet the  problem like this: mmcv-full , pycuda  could not build wheels for that,which is required to install pyproject.toml-based projects.   your problems  ,i think  just delete the version ,that is  ok .

**Comment by zhujunli1993** [comment]
Could you please provide some examples of problems you faced?
